<?php /** @var \ParadoxLabs\CyberSource\Block\Secureaccept\Complete $block */ ?>
<?php
$message = [
    'success' => false,
    'canceled' => false,
    'error' => '',
    'card' => [],
];

try {
    $card = $block->getCard();

    $message['success'] = true;
    $message['card'] = [
        'id' => $card->getHash(),
        'label' => $card->getLabel(),
        'selected' => false,
        'new' => true,
        'type' => $card->getType(),
        'cc_bin' => $card->getAdditional('cc_bin'),
        'cc_last_4' => $card->getAdditional('cc_last_4'),
    ];
} catch (\Exception $e) {
    $message['error'] = $e->getMessage();
}
?>
<?php if (!empty($message['error'])): ?>
    <div id="cybersource-complete-results" style="display:none" class="messages">
        <div class="error-msg message-error error message">
            <span><?= $block->escapeHtml(__('ERROR: %1', $message['error'])) ?></span>
        </div>
    </div>
<?php else: ?>
    <p id="cybersource-complete-results" style="display:none">
        <?= $block->escapeHtml(__('%1 entered successfully.', $card->getLabel())) ?>
    </p>
<?php endif; ?>

<script type="text/javascript">
    /**
     * Show the results after 3 seconds in the event that the communicator fails, but don't otherwise, to avoid visual
     * disruption (blinky page).
     */
    setTimeout(
        function () {
            document.getElementById('cybersource-complete-results').style.display = 'block';
        },
        3000
    );

    /**
     * Send the results out of frame up to the parent page.
     */
    require(
        ['jquery'],
        function($) {
            var communicator = window.top.jQuery('#paradoxlabs_cybersource-communicator', window.top.document);
            communicator.val('<?= json_encode($message) ?>');
            communicator.trigger('change');
        }
    )
</script>
