<?php /** @var \ParadoxLabs\CyberSource\Block\Secureaccept\Complete $block */ ?>
<?php
$message = [
    'success' => false,
    'canceled' => false,
    'error' => '',
    'card' => [],
];

try {
    $card = $block->getCard();

    $message['success'] = true;
    $message['card'] = [
        'id' => $card->getHash(),
        'label' => $card->getLabel(),
        'selected' => false,
        'type' => $card->getType(),
    ];
} catch (\Exception $e) {
    // TODO: Proper error handling
    $message['error'] = $e->getMessage();
}
?>
<?php if (!empty($message['error'])): ?>
    <div class="messages">
        <div class="error-msg message-error error message">
            <span><?= $block->escapeHtml(__('ERROR: %1', $error)) ?></span>
        </div>
    </div>
<?php else: ?>
    <p><?= $block->escapeHtml(__('Card %1 entered successfully.', $card->getLabel())) ?></p>
<?php endif; ?>

<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var communicator = window.top.jQuery('#paradoxlabs_cybersource-communicator', window.top.document);
            communicator.val('<?= json_encode($message) ?>');
            communicator.trigger('change');
        }
    )
</script>
