<?php
/** @var \ParadoxLabs\CyberSource\Block\Form\Cc $block */
/** @var \Magento\Framework\Escaper $escaper */

use Magento\Framework\View\Helper\SecureHtmlRenderer;

$code        = $escaper->escapeHtmlAttr($block->getMethodCode());
$image       = $block->getBrandingImage();
$storedCards = $block->getStoredCards();
?>
<div id="payment_form_<?= /* @noEscape */
$code ?>" class="admin__page-section-item checkout-payment-method payment_form_<?= /* @noEscape */
$code ?>" data-mage-init='{
    "tokenbaseForm": {
        "code":"<?= /* @noEscape */
$code ?>",
        "validateForm": false
    },
    "cybersourceLegacyForm": {
        "target": "<?= /* @noEscape */
$code ?>_iframe",
        "paramUrl": "<?= $escaper->escapeJs($block->getUrl('pdl_cybs/secureAccept/getParams')) ?>",
        "fingerprintUrl": null
    }
}'>
    <input id="<?= /* @noEscape */
    $code ?>-payment-method" type="hidden" name="payment[method]" value="<?= /* @noEscape */
    $code ?>"/>
    <input type="hidden" name="source" value="checkout"/>
    <?= /* @noEscape */
    $block->getBlockHtml('formkey') ?>

    <fieldset class="admin__fieldset payment items ccard">
        <?php if ($image): ?>
            <div class="page-actions">
                <img src="<?= $escaper->escapeUrl($image); ?>"/>
            </div>
        <?php endif; ?>
        <div class="admin__field">
            <div class="admin__field-control control">
                <select id="<?= /* @noEscape */
                $code ?>-card-id" name="payment[card_id]" class="select admin__control-select">
                    <option value='' <?php if (count($storedCards) > 1
                    && $block->getInfoData('tokenbase_id')
                    == ''): ?>selected="selected"<?php endif; ?>><?= $escaper->escapeHtml(__('Add new card')) ?></option>
                    <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
                    <?php foreach ($storedCards as $card): ?>
                        <?php $card = $card->getTypeInstance(); ?>
                        <option value="<?= $escaper->escapeHtmlAttr($card->getHash()) ?>"
                                data-cc_bin="<?= $escaper->escapeHtmlAttr($card->getAdditional('cc_bin')) ?>"
                                data-cc_last4="<?= $escaper->escapeHtmlAttr($card->getAdditional('cc_last4')) ?>"
                                data-new="false"
                                data-type="<?= $escaper->escapeHtmlAttr($card->getType()) ?>"
                                <?php if ($card->getId() == $block->getInfoData('tokenbase_id')
                                || count($storedCards)
                                == 1): ?>selected="selected"<?php endif; ?>>
                            <?= $escaper->escapeHtml($card->getLabel()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="admin__field _required card hide-if-card-selected">
            <div class="admin__field-control control">
                <iframe src="about:blank" id="<?= /* @noEscape */
                $code ?>_iframe" name="<?= /* @noEscape */
                $code ?>_iframe"></iframe>
                <p id="<?= /* @noEscape */
                $code ?>_warning" class="admin__field-control message message-error error "></p>
            </div>
        </div>
        <?= /* @noEscape */
        $block->getChildHtml() ?>
        <?php if ($block->hasVerification() && $block->getMethod()->getConfigData('require_ccv')): ?>
            <div class="admin__field _required cvv">
                <label class="label admin__field-label" for="<?= /* @noEscape */
                $code ?>-cc-cid"><span><?= $escaper->escapeHtml(__('Card Verification Number')) ?></span></label>
                <div class="admin__field-control control">
                    <div class="v-fix">
                        <input type="hidden" name="payment[cc_type]" id="<?= /* @noEscape */
                        $code ?>-cc-type" value=""/>
                        <input type="text" title="<?= $escaper->escapeHtmlAttr(
                            __('Card Verification Number')
                        ) ?>" class="input-text admin__control-text cvv required-entry" id="<?= /* @noEscape */
                        $code ?>-cc-cid" name="payment[cc_cid]" value="<?= $escaper->escapeHtmlAttr(
                            $block->getInfoData('cc_cid')
                        ); ?>" data-validate='{"required-number":true}' autocomplete="cc-csc"/>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!$block->isGuestCheckout()): ?>
            <div class="admin__field save">
                <div class="admin__field-control control">
                    <?php if ($block->getMethod()->getConfigData('allow_unsaved')): ?>
                        <input type="hidden" name="payment[save]" value="0"/>
                        <input type="checkbox" title="<?= $escaper->escapeHtmlAttr(
                            __('Save for next time')
                        ) ?>" class="input-checkbox" id="<?= /* @noEscape */
                        $code ?>-save" name="payment[save]" value="1" <?php if ($block->getMethod()->getConfigData(
                            'savecard_opt_out'
                        )
                        && $block->getInfoData('save') !== 0): ?>checked="checked"<?php endif; ?> />
                        <label for="<?= /* @noEscape */
                        $code ?>-save"><?= $escaper->escapeHtml(__('Save for next time')) ?></label>
                    <?php else: ?>
                        <input type="hidden" name="payment[save]" value="1"/>
                        <label class="label admin__field-label" for="<?= /* @noEscape */
                        $code ?>-save"><?= $escaper->escapeHtml(
                                __('For your convenience, this data will be stored securely by our payment processor.')
                            ) ?></label>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
</div>
<?php if (isset($secureRenderer) && $secureRenderer instanceof SecureHtmlRenderer): ?>
    <?= /* @noEscape */
    $secureRenderer->renderStyleAsTag('display:none', '#payment_form_' . $code) ?>
<?php else: ?>
    <script>
        if (document.querySelector('#payment_form_<?= /* @noEscape */ $code ?>') instanceof Element) {
            document.querySelector('#payment_form_<?= /* @noEscape */ $code ?>').style.display = 'none';
        }
    </script>
<?php endif; ?>
